# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HEXAmainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(600, 504)
        MainWindow.setAcceptDrops(True)
        MainWindow.setWindowIcon(QtGui.QIcon("icons/HEXA50.png"))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.casesBox = QtWidgets.QComboBox(self.tab)
        self.casesBox.setGeometry(QtCore.QRect(60, 220, 311, 31))
        self.casesBox.setObjectName("casesBox")
        self.fileEdit = QtWidgets.QLineEdit(self.tab)
        self.fileEdit.setGeometry(QtCore.QRect(60, 270, 311, 31))
        self.fileEdit.setObjectName("fileEdit")
        self.updateButton = QtWidgets.QPushButton(self.tab)
        self.updateButton.setGeometry(QtCore.QRect(400, 220, 121, 31))
        self.updateButton.setObjectName("updateButton")
        self.fileButton = QtWidgets.QPushButton(self.tab)
        self.fileButton.setGeometry(QtCore.QRect(400, 270, 121, 31))
        self.fileButton.setObjectName("fileButton")
        self.startButton = QtWidgets.QPushButton(self.tab)
        self.startButton.setGeometry(QtCore.QRect(180, 320, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.startButton.setFont(font)
        self.startButton.setObjectName("startButton")
        self.imagelabel = QtWidgets.QLabel(self.tab)
        self.imagelabel.setGeometry(QtCore.QRect(180, 20, 201, 181))
        self.imagelabel.setText("")
        self.imagelabel.setPixmap(QtGui.QPixmap("icons/HEXA200.png"))
        self.imagelabel.setObjectName("imagelabel")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setGeometry(QtCore.QRect(20, 22, 541, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 80, 101, 91))
        self.lcdNumber.setDigitCount(2)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 190, 101, 91))
        self.lcdNumber_2.setDigitCount(2)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_3.setGeometry(QtCore.QRect(20, 300, 101, 91))
        self.lcdNumber_3.setDigitCount(2)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(140, 80, 171, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(140, 190, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(140, 300, 161, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(460, 370, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.resultEdit = QtWidgets.QTextEdit(self.tab_2)
        self.resultEdit.setGeometry(QtCore.QRect(10, 10, 551, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resultEdit.setFont(font)
        self.resultEdit.setReadOnly(True)
        self.resultEdit.setObjectName("resultEdit")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuResult = QtWidgets.QMenu(self.menuBar)
        self.menuResult.setObjectName("menuResult")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout.setIcon(QtGui.QIcon("icons/about.png"))
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionQuit.setIcon(QtGui.QIcon("icons/exit.png"))
        self.actionQuit.setShortcut("Ctrl+Q")
        self.actionDelete_Cases = QtWidgets.QAction(MainWindow)
        self.actionDelete_Cases.setObjectName("actionDelete_Cases")
        self.actionDelete_Cases.setIcon(QtGui.QIcon("icons/delete.png"))
        self.actionDelete_Cases.setShortcut("Ctrl+D")
        self.actionClear_Result = QtWidgets.QAction(MainWindow)
        self.actionClear_Result.setObjectName("actionClear_Result")
        self.actionClear_Result.setIcon(QtGui.QIcon("icons/clear.png"))
        self.actionClear_Result.setShortcut("Ctrl+C")
        self.actionSave_Result = QtWidgets.QAction(MainWindow)
        self.actionSave_Result.setObjectName("actionSave_Result")
        self.actionSave_Result.setIcon(QtGui.QIcon("icons/save.png"))
        self.actionSave_Result.setShortcut("Ctrl+S")
        self.menuFile.addAction(self.actionDelete_Cases)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuResult.addAction(self.actionClear_Result)
        self.menuResult.addAction(self.actionSave_Result)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuResult.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HEXA-A Test Tool"))
        self.updateButton.setText(_translate("MainWindow", "Online Update"))
        self.fileButton.setText(_translate("MainWindow", "Select File"))
        self.startButton.setText(_translate("MainWindow", "Start Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dashboard"))
        self.label.setText(_translate("MainWindow", "Passed Cases"))
        self.label_2.setText(_translate("MainWindow", "Warning Cases"))
        self.label_3.setText(_translate("MainWindow", "Failed Cases"))
        self.pushButton.setText(_translate("MainWindow", "Restart Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Result"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Log"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuResult.setTitle(_translate("MainWindow", "Result"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionDelete_Cases.setText(_translate("MainWindow", "Delete Offline Cases"))
        self.actionClear_Result.setText(_translate("MainWindow", "Clear Result"))
        self.actionSave_Result.setText(_translate("MainWindow", "Save Result"))

class Ui_aboutgui(object):
    def setupUi(self, aboutgui):
        aboutgui.setObjectName("aboutgui")
        aboutgui.resize(422, 300)
        aboutgui.setWindowIcon(QtGui.QIcon("icons/HEXA50.png"))
        self.buttonBox = QtWidgets.QDialogButtonBox(aboutgui)
        self.buttonBox.setGeometry(QtCore.QRect(20, 260, 381, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(aboutgui)
        self.label.setGeometry(QtCore.QRect(160, 10, 111, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icons/HEXA100.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(aboutgui)
        self.label_2.setGeometry(QtCore.QRect(140, 110, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(aboutgui)
        self.label_3.setGeometry(QtCore.QRect(130, 200, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(aboutgui)
        self.label_4.setGeometry(QtCore.QRect(150, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(aboutgui)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 111, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(aboutgui)
        self.label_6.setGeometry(QtCore.QRect(140, 150, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(aboutgui)
        self.buttonBox.accepted.connect(aboutgui.accept)
        self.buttonBox.rejected.connect(aboutgui.reject)
        QtCore.QMetaObject.connectSlotsByName(aboutgui)

    def retranslateUi(self, aboutgui):
        _translate = QtCore.QCoreApplication.translate
        aboutgui.setWindowTitle(_translate("aboutgui", "HEXA-A Test Tool v1.0"))
        self.label_2.setText(_translate("aboutgui", "HEXA-A"))
        self.label_3.setText(_translate("aboutgui", "Copyright © HEXA-A Team"))
        self.label_4.setText(_translate("aboutgui", "<a href=\"http://hexa-a.com/\">Online Test Tool</a>"))
        self.label_5.setText(_translate("aboutgui", "<a href=\'mailto:support@hexa-a.com\'>support@hexa-a.com</a>"))
        self.label_6.setText(_translate("aboutgui", "Test Tool"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

